import pandas as pd
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parents[1]

OUTPUT_DIR = BASE_DIR / "outputs" / "reports"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

dictionary = [

    # powerbi_orders
    ["powerbi_orders", "order_id", "VARCHAR",
     "Unique order identifier"],

    ["powerbi_orders", "customer_unique_id", "VARCHAR",
     "Unique customer identifier"],

    ["powerbi_orders", "order_purchase_timestamp", "TIMESTAMP",
     "Order purchase datetime"],

    ["powerbi_orders", "actual_delivery_days", "INTEGER",
     "Actual delivery duration in days"],

    ["powerbi_orders", "delivery_delay_days", "INTEGER",
     "Difference between actual and estimated delivery days"],

    ["powerbi_orders", "is_delayed", "INTEGER",
     "1 = delayed, 0 = on-time"],

    ["powerbi_orders", "review_score", "INTEGER",
     "Customer review score (1-5)"],

    # powerbi_revenue

    ["powerbi_revenue", "order_revenue", "DOUBLE",
     "Revenue generated by order"],

    ["powerbi_revenue", "order_month_date", "DATE",
     "Monthly aggregation date"],

    # powerbi_categories

    ["powerbi_categories", "category", "VARCHAR",
     "Product category name"],

    ["powerbi_categories", "product_revenue", "DOUBLE",
     "Revenue generated by category"],

    ["powerbi_categories", "avg_review", "DOUBLE",
     "Average review score"],

    ["powerbi_categories", "delay_rate", "DOUBLE",
     "Percentage of delayed deliveries"],

    # powerbi_customers

    ["powerbi_customers", "recency", "INTEGER",
     "Days since last purchase"],

    ["powerbi_customers", "frequency", "INTEGER",
     "Number of purchases"],

    ["powerbi_customers", "monetary", "DOUBLE",
     "Total customer spending"],

    ["powerbi_customers", "customer_segment", "VARCHAR",
     "RFM customer segment"],

    # executive KPI

    ["powerbi_executive_kpi", "total_orders", "INTEGER",
     "Total number of completed orders"],

    ["powerbi_executive_kpi", "total_revenue", "DOUBLE",
     "Total platform revenue"],

    ["powerbi_executive_kpi", "aov", "DOUBLE",
     "Average order value"],

    ["powerbi_executive_kpi", "avg_review_score", "DOUBLE",
     "Average customer review score"],

    ["powerbi_executive_kpi", "delay_rate", "DOUBLE",
     "Percentage of delayed orders"]

]

df = pd.DataFrame(
    dictionary,
    columns=[
        "dataset",
        "column_name",
        "data_type",
        "business_definition"
    ]
)

output_path = OUTPUT_DIR / "data_dictionary.csv"

df.to_csv(
    output_path,
    index=False
)

print("=" * 60)
print("Data Dictionary Created")
print("=" * 60)

print(df)

print(f"\nSaved to:\n{output_path}")